export const hints = [
  {
    id: 'h-1',
    title: 'Suraskite vieta',
    description: 'Siai vietai siandien jau 85-eri. Per siuos metus joje uzaugo ne vienas scenos profesionalas XX a. pradzioje sioje vietoje buvo isikurusi moteru gimnazija.',
    iconPath: 'far fa-star',
    imagePath: '',
    objectImagePath: '',
    answerText: 'Pateikite dailininko varda, pavarde',
    answer: 'Samuelis',
    answered: false,
    congrats: {
      title: "Samuelis Bakas",
      description: "Nuo pat vaikystes sis dailininkas domejosi piesimu. Antrojo pasaulinio karo metais su visa siema pateko i Vilniaus geta. Nors ir apsuptas gresmingos ir ziaurios realybes astuoniu metu Samuelis buvo aprupintas popieriumi, piestukais, akvarele ir galejo testi savo pamegta uzsiemima. Cia sulauke ir pirmojo savo kurybos pripazinimo - 1943m. gete surengtoje profesionaliu dailininku parodoje greta ju darbu puikavosi 10-mecio Samuelio Bako piesiniai"
    }
  },
  {
    id: 'h-2',
    title: '',
    description: '',
    iconPath: 'fas fa-paint-brush',
    imagePath: '',
    objectImagePath: '',
    answerText: 'Pateikite dailininko varda, pavarde',
    answer: '',
    answered: false,
  },
  {
    id: 'h-3',
    title: '',
    description: '',
    iconPath: 'fas fa-users',
    imagePath: '',
    objectImagePath: '',
    answerText: 'Pateikite dailininko varda, pavarde',
    answer: '',
    answered: false,
  },
  {
    id: 'h-4',
    title: '',
    description: '',
    iconPath: 'fas fa-theater-masks',
    imagePath: '',
    objectImagePath: '',
    answerText: 'Pateikite dailininko varda, pavarde',
    answer: '',
    answered: false,
  },
  {
    id: 'h-5',
    title: '',
    description: '',
    iconPath: 'fas fa-music',
    imagePath: '',
    objectImagePath: '',
    answerText: 'Pateikite dailininko varda, pavarde',
    answer: '',
    answered: false,
  },
]